"use client";
import {useState} from "react";import {useRouter} from "next/navigation";import RichTextEditor from "./RichTextEditor";
type Lesson={id:string;title:string;description:string|null;type:string;videoUrl:string|null;content:string|null;durationMin:number;sortOrder:number};type Module={id:string;title:string;sortOrder:number;lessons:Lesson[]};type Course={id:string;slug:string;title:string;shortDescription:string;description:string;level:string;durationHours:number;pricePaise:number;mode:string;published:boolean;featured:boolean;thumbnailUrl:string|null;modules:Module[]};
const types=["VIDEO","ARTICLE","PDF","LIVE","LINK","QUIZ","ASSIGNMENT"];
export default function CourseBuilder({course:initial}:{course:Course}){const router=useRouter();const[course,setCourse]=useState(initial);const[busy,setBusy]=useState("");const[editing,setEditing]=useState(false);const[courseForm,setCourseForm]=useState({title:initial.title,slug:initial.slug,shortDescription:initial.shortDescription,description:initial.description,level:initial.level,durationHours:String(initial.durationHours),price:String(initial.pricePaise/100),mode:initial.mode,featured:initial.featured,published:initial.published});const[lessonDraft,setLessonDraft]=useState<Record<string,{title:string;type:string;durationMin:string;videoUrl:string;content:string}>>({});const[editingLessonId,setEditingLessonId]=useState<string|null>(null);const[lessonEditForm,setLessonEditForm]=useState<{moduleId:string;title:string;description:string;type:string;videoUrl:string;content:string;durationMin:string}|null>(null);
 const call=async(url:string,method:string="PATCH",body?:unknown)=>{setBusy(url);const r=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));setBusy("");if(!r.ok)throw new Error(d.error||"Request failed");return d};
 async function saveCourse(){try{const d=await call(`/api/admin/courses/${course.id}`,"PATCH",courseForm);setCourse({...course,...d.course});alert("Course saved")}catch(e){alert(e instanceof Error?e.message:"Save failed")}}
 async function addModule(){const title=prompt("Module title");if(!title)return;try{const d=await call(`/api/admin/courses/${course.id}/modules`,"POST",{title});setCourse(c=>({...c,modules:[...c.modules,d.module]}))}catch(e){alert(e instanceof Error?e.message:"Could not add module")}}
 async function deleteModule(id:string){if(!confirm("Delete this module and all its lessons?"))return;try{await call(`/api/admin/courses/${course.id}/modules/${id}`,"DELETE");setCourse(c=>({...c,modules:c.modules.filter(m=>m.id!==id)}))}catch(e){alert(e instanceof Error?e.message:"Could not delete module")}}
 async function moveModule(id:string,dir:-1|1){const i=course.modules.findIndex(m=>m.id===id);const j=i+dir;if(j<0||j>=course.modules.length)return;const ids=course.modules.map(m=>m.id);[ids[i],ids[j]]=[ids[j],ids[i]];try{await call(`/api/admin/courses/${course.id}/modules/${id}`,"PATCH",{sortOrder:j+1,orderedIds:ids});setCourse(c=>({...c,modules:ids.map((x,k)=>({...c.modules.find(m=>m.id===x)!,sortOrder:k+1}))}))}catch(e){alert(e instanceof Error?e.message:"Could not reorder")}}
 async function addLesson(m:Module){const d=lessonDraft[m.id]||{title:"",type:"VIDEO",durationMin:"0",videoUrl:"",content:""};if(!d.title.trim())return alert("Enter a lesson title first");try{const r=await call(`/api/admin/courses/${course.id}/modules/${m.id}/lessons`,"POST",d);setCourse(c=>({...c,modules:c.modules.map(x=>x.id===m.id?{...x,lessons:[...x.lessons,r.lesson]}:x)}));setLessonDraft({...lessonDraft,[m.id]:{title:"",type:"VIDEO",durationMin:"0",videoUrl:"",content:""}})}catch(e){alert(e instanceof Error?e.message:"Could not add lesson")}}
 async function deleteLesson(m:Module,l:Lesson){if(!confirm(`Delete lesson “${l.title}”?`))return;try{await call(`/api/admin/courses/${course.id}/modules/${m.id}/lessons/${l.id}`,"DELETE");setCourse(c=>({...c,modules:c.modules.map(x=>x.id===m.id?{...x,lessons:x.lessons.filter(y=>y.id!==l.id)}:x)}))}catch(e){alert(e instanceof Error?e.message:"Could not delete lesson")}}
 async function moveLesson(m:Module,l:Lesson,dir:-1|1){const i=m.lessons.findIndex(x=>x.id===l.id),j=i+dir;if(j<0||j>=m.lessons.length)return;const ids=m.lessons.map(x=>x.id);[ids[i],ids[j]]=[ids[j],ids[i]];try{await call(`/api/admin/courses/${course.id}/modules/${m.id}/lessons/${l.id}`,"PATCH",{sortOrder:j+1,orderedIds:ids});setCourse(c=>({...c,modules:c.modules.map(x=>x.id===m.id?{...x,lessons:ids.map((id,k)=>({...x.lessons.find(y=>y.id===id)!,sortOrder:k+1}))}:x)}))}catch(e){alert(e instanceof Error?e.message:"Could not reorder lesson")}}
 async function togglePublish(){try{const d=await call(`/api/admin/courses/${course.id}`,"PATCH",{published:!course.published});setCourse({...course,...d.course});setCourseForm({...courseForm,published:d.course.published})}catch(e){alert(e instanceof Error?e.message:"Could not update publish state")}}
 
 function openEditLesson(m:Module,l:Lesson){setEditingLessonId(l.id);setLessonEditForm({moduleId:m.id,title:l.title,description:l.description||"",type:l.type,videoUrl:l.videoUrl||"",content:l.content||"",durationMin:String(l.durationMin)})}
 
 function closeEditLesson(){setEditingLessonId(null);setLessonEditForm(null)}
 
 async function saveEditedLesson(){if(!editingLessonId||!lessonEditForm||!lessonEditForm.title.trim())return alert("Lesson title is required");try{const d=await call(`/api/admin/courses/${course.id}/modules/${lessonEditForm.moduleId}/lessons/${editingLessonId}`,"PATCH",{title:lessonEditForm.title,description:lessonEditForm.description,type:lessonEditForm.type,videoUrl:lessonEditForm.videoUrl,content:lessonEditForm.content,durationMin:lessonEditForm.durationMin});setCourse(c=>({...c,modules:c.modules.map(m=>m.id===lessonEditForm.moduleId?{...m,lessons:m.lessons.map(l=>l.id===editingLessonId?{...l,...d.lesson}:l)}:m)}));closeEditLesson();alert("Lesson updated")}catch(e){alert(e instanceof Error?e.message:"Could not save lesson")}}
 
 return <div>
 <div className="card builder-toolbar"><div><strong>{course.published?"Published":"Draft"}</strong><span className="muted"> · {course.modules.length} modules · {course.modules.reduce((n,m)=>n+m.lessons.length,0)} lessons</span></div><div style={{display:"flex",gap:8}}><button className="btn btn-secondary" onClick={()=>setEditing(!editing)}>{editing?"Close Course Details":"Edit Course Details"}</button><button className="btn btn-primary" onClick={togglePublish}>{course.published?"Unpublish":"Publish Course"}</button></div></div>
 {editing&&<div className="card" style={{marginTop:15}}><h2>Course Details</h2><div className="grid grid-2"><label>Title<input className="input" value={courseForm.title} onChange={e=>setCourseForm({...courseForm,title:e.target.value})}/></label><label>Slug<input className="input" value={courseForm.slug} onChange={e=>setCourseForm({...courseForm,slug:e.target.value})}/></label><label>Level<input className="input" value={courseForm.level} onChange={e=>setCourseForm({...courseForm,level:e.target.value})}/></label><label>Duration<input className="input" type="number" value={courseForm.durationHours} onChange={e=>setCourseForm({...courseForm,durationHours:e.target.value})}/></label><label>Price ₹<input className="input" type="number" value={courseForm.price} onChange={e=>setCourseForm({...courseForm,price:e.target.value})}/></label><label>Mode<select className="input" value={courseForm.mode} onChange={e=>setCourseForm({...courseForm,mode:e.target.value})}>{["ONLINE","OFFLINE","HYBRID","SELF_PACED"].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Short description<RichTextEditor value={courseForm.shortDescription} onChange={v=>setCourseForm({...courseForm,shortDescription:v})} placeholder="Write a concise formatted course summary..." minHeight={110}/></label><label>Description<RichTextEditor value={courseForm.description} onChange={v=>setCourseForm({...courseForm,description:v})} placeholder="Write the complete course description..." minHeight={220}/></label><label><input type="checkbox" checked={courseForm.featured} onChange={e=>setCourseForm({...courseForm,featured:e.target.checked})}/> Featured</label><button className="btn btn-primary" onClick={saveCourse}>Save Course Details</button></div>}
 <div className="builder-head"><h2>Curriculum</h2><button className="btn btn-primary" onClick={addModule}>+ Add Module</button></div>
 {course.modules.map((m,mi)=><div className="card builder-module" key={m.id}><div className="module-head"><div><span className="badge">MODULE {mi+1}</span><h3>{m.title}</h3></div><div style={{display:"flex",gap:6}}><button className="btn btn-secondary" onClick={()=>moveModule(m.id,-1)}>↑</button><button className="btn btn-secondary" onClick={()=>moveModule(m.id,1)}>↓</button><button className="btn btn-danger" onClick={()=>deleteModule(m.id)}>Delete</button></div></div>
 {m.lessons.map((l,li)=><div className="builder-lesson" key={l.id}><div><strong>{li+1}. {l.title}</strong><span className="badge" style={{marginLeft:8}}>{l.type}</span><span className="muted" style={{marginLeft:8}}>{l.durationMin} min</span></div><div style={{display:"flex",gap:5}}><button className="btn btn-secondary" onClick={()=>openEditLesson(m,l)}>Edit</button><button className="btn btn-secondary" onClick={()=>moveLesson(m,l,-1)}>↑</button><button className="btn btn-secondary" onClick={()=>moveLesson(m,l,1)}>↓</button><button className="btn btn-danger" onClick={()=>deleteLesson(m,l)}>Delete</button></div></div>)}
 <div className="lesson-add"><input className="input" placeholder="Lesson title" value={(lessonDraft[m.id]?.title)||""} onChange={e=>setLessonDraft({...lessonDraft,[m.id]:{...(lessonDraft[m.id]||{type:"VIDEO",durationMin:"0",videoUrl:"",content:""}),title:e.target.value}})}/><select className="input" value={lessonDraft[m.id]?.type||"VIDEO"} onChange={e=>setLessonDraft({...lessonDraft,[m.id]:{...(lessonDraft[m.id]||{title:"",durationMin:"0",videoUrl:"",content:""}),type:e.target.value}})}>{types.map(t=><option key={t}>{t}</option>)}</select><input className="input" type="number" min="0" placeholder="Minutes" value={lessonDraft[m.id]?.durationMin||"0"} onChange={e=>setLessonDraft({...lessonDraft,[m.id]:{...(lessonDraft[m.id]||{title:"",type:"VIDEO",videoUrl:"",content:""}),durationMin:e.target.value}})}/><input className="input" placeholder="Video / PDF / resource URL" value={lessonDraft[m.id]?.videoUrl||""} onChange={e=>setLessonDraft({...lessonDraft,[m.id]:{...(lessonDraft[m.id]||{title:"",type:"VIDEO",durationMin:"0",content:""}),videoUrl:e.target.value}})}/><button className="btn btn-primary" onClick={()=>addLesson(m)}>Add Lesson</button></div>
 </div>)}
 
 {editingLessonId&&lessonEditForm&&<div className="card" style={{marginTop:15}}><h2>Edit Lesson</h2><div className="grid grid-2"><label>Title<input className="input" value={lessonEditForm.title} onChange={e=>setLessonEditForm({...lessonEditForm,title:e.target.value})}/></label><label>Lesson Type<select className="input" value={lessonEditForm.type} onChange={e=>setLessonEditForm({...lessonEditForm,type:e.target.value})}>{types.map(t=><option key={t}>{t}</option>)}</select></label><label>Duration (minutes)<input className="input" type="number" min="0" value={lessonEditForm.durationMin} onChange={e=>setLessonEditForm({...lessonEditForm,durationMin:e.target.value})}/></label><label>Resource URL<input className="input" placeholder="Video URL, PDF link, or resource URL" value={lessonEditForm.videoUrl} onChange={e=>setLessonEditForm({...lessonEditForm,videoUrl:e.target.value})}/></label></div><label>Description<input className="input" placeholder="Brief description of the lesson" value={lessonEditForm.description} onChange={e=>setLessonEditForm({...lessonEditForm,description:e.target.value})}/></label>{["ARTICLE"].includes(lessonEditForm.type)&&<label>Content (Rich Text)<RichTextEditor value={lessonEditForm.content} onChange={v=>setLessonEditForm({...lessonEditForm,content:v})} placeholder="Write lesson content..." minHeight={250}/></label>}{["QUIZ","ASSIGNMENT"].includes(lessonEditForm.type)&&<label>Content/Instructions (Rich Text)<RichTextEditor value={lessonEditForm.content} onChange={v=>setLessonEditForm({...lessonEditForm,content:v})} placeholder="Write quiz questions or assignment instructions..." minHeight={250}/></label>}<div style={{display:"flex",gap:8,marginTop:15}}><button className="btn btn-primary" onClick={saveEditedLesson}>Save Lesson</button><button className="btn btn-secondary" onClick={closeEditLesson}>Cancel</button></div></div>}
 
 {!course.modules.length&&<div className="card">No modules yet. Click <strong>Add Module</strong> to start building the curriculum.</div>}
 </div>}
